pipeline {

    agent {
        label 'slave01'
    }

    environment {
        IMAGE_NAME = 'ghcr.io/anton-dmytryshyn/my-tools:1.0'
    }

    stages {

        stage('Docker build') {
            steps {
                sh '''
                    docker build -t $IMAGE_NAME docker-image-pipeline
                '''
            }
        }

        stage('Docker login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github_access_for_jenkins_anton_dmytryshyn',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'TOKEN'
                )]) {

                    sh '''
                        echo $TOKEN | docker login ghcr.io -u $USERNAME --password-stdin
                    '''
                }
            }
        }

        stage('Docker push') {
            steps {
                sh '''
                    docker push $IMAGE_NAME
                '''
            }
        }
    }
}
